// Données des animaux (à compléter avec les informations réelles)
const especeData = {
  Méghalayen: [
    {
      name: "Ane",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description:
        "L'histoire de la capsule à bière remonte au 19e siècle, lorsque les brasseurs ont cherché un moyen de préserver la fraîcheur et la carbonatation de leurs précieux breuvages. En 1892, William Painter a inventé la première capsule en métal, également connue sous le nom de couronne. Elle était munie d'un joint en caoutchouc et d'un levier qui permettait de sceller hermétiquement les bouteilles. ",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Northgrippien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Greenlandien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  PléistocèneSupérieur: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  PléistocèneMoyen: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Calabrien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Gélasien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Plaisancien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Zancléen: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Messinien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Tortonien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Serravallien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Langhien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],

  Burdigalien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Aquitanien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Chattien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Rupélien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Priabonien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Bartonien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Lutétien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Yprésien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Thanétien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Sélandien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Danien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Maastrichtien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Campanien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Santonien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Coniacien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Turonien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Cénomanien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Albien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Aptien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Barrémien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Hauterivien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Valanginien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Berriasien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Tithonien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Kimméridgien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Oxfordien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Callovien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Bathonien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Bajocien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Aalénien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Toarcien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Pliensbachien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Sinémurien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Hettangien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Rhétien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],

  Norien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Carnien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Ladinien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Anisien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Olénékien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Indusien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Changhsingien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Wuchiapingien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Capitanien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Wordien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Roadien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Kungurien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Artinskien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Sakmarien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Assélien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Gzhélien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Kasimovien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Moscovien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Bachkirien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],

  Serpukhovien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Viséen: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Tournaisien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Famennien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Frasnien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Givétien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Eifélien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Emsien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Praguien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Lochkovien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Pridolien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Ludfordien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Gorstien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Homérien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Sheinwoodien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Télychien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],

  Aéronien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],

  Rhuddanien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],

  Hirnantien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Katien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Sandbien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Darriwilien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Dapingien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Floien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Trémadocien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Etage10: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Jiangshanien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Paibien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Guzhangien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Drumien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Wuliuen: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Etage4: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Etage3: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Etage2: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
  Fortunien: [
    {
      name: "espece 12",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
    {
      name: "espece 5",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "lien_de_l'image",
      description: "Description de l'espece 1",
    },
  ],
};
