// Données des animaux (à compléter avec les informations réelles)
const especeData = {
  Méghalayen: [
    {
      name: "Ane",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "",
      description: "",
    },
  ],
  Northgrippien: [
    {
      name: "",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Northgrippien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "",
      description: "",
    },
  ],
  Greenlandien: [
    {
      name: "",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Greenlandien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Quaternaire",
      epoque: "Holocène",
      etage: "Méghalayen",
      image: "",
      description: "",
    },
  ],
  PléistocèneSupérieur: [
    {
      name: "",
      period: "Quaternaire",
      epoque: "Pléistocène",
      etage: "Pléistocène Supérieur",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Quaternaire",
      epoque: "Pléistocène",
      etage: "Pléistocène Supérieur",
      image: "",
      description: "",
    },
  ],
  PléistocèneMoyen: [
    {
      name: "",
      period: "Quaternaire",
      epoque: "Pléistocène",
      etage: "Pléistocène Moyen",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Quaternaire",
      epoque: "Pléistocène",
      etage: "Pléistocène Moyen",
      image: "",
      description: "",
    },
  ],
  Calabrien: [
    {
      name: "",
      period: "Quaternaire",
      epoque: "Pléistocène",
      etage: "Calabrien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Quaternaire",
      epoque: "Pléistocène",
      etage: "Calabrien",
      image: "",
      description: "",
    },
  ],
  Gélasien: [
    {
      name: "",
      period: "Quaternaire",
      epoque: "Pléistocène",
      etage: "Gélasien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Quaternaire",
      epoque: "Pléistocène",
      etage: "Gélasien",
      image: "",
      description: "",
    },
  ],

  Plaisancien: [
    {
      name: "",
      period: "Néogène",
      epoque: "Pliocène",
      etage: "Plaisancien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Néogène",
      epoque: "Pliocène",
      etage: "Plaisancien",
      image: "",
      description: "",
    },
  ],
  Zancléen: [
    {
      name: "",
      period: "Néogène",
      epoque: "Pliocène",
      etage: "Zancléen",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Néogène",
      epoque: "Pliocène",
      etage: "Zancléen",
      image: "",
      description: "",
    },
  ],
  Messinien: [
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Messinien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Messinien",
      image: "",
      description: "",
    },
  ],
  Tortonien: [
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Tortonien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Tortonien",
      image: "",
      description: "",
    },
  ],
  Serravallien: [
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Serravallien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Serravallien",
      image: "",
      description: "",
    },
  ],
  Langhien: [
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Langhien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Langhien",
      image: "",
      description: "",
    },
  ],

  Burdigalien: [
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Burdigalien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Burdigalien",
      image: "",
      description: "",
    },
  ],
  Aquitanien: [
    {
      name: "Deinotherium",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Aquitanien",
      image: "/images/Deinotherium.jpg",
      description:
        "Le Deinotherium était un genre d'éléphant préhistorique qui a vécu pendant le Miocène, il y a environ 23 à 5 millions d'années. Il était caractérisé par ses défenses inférieures courbées vers l'avant, contrairement aux éléphants modernes dont les défenses sont incurvées vers le bas. Le Deinotherium avait une trompe allongée et une taille impressionnante, pouvant atteindre jusqu'à 4 mètres de hauteur à l'épaule. Les plus gros spécimen devaient peser entre 12 et 15 tonnes. C'était l'un des plus grands mammifères terrestres de son époque.",
    },
    {
      name: "",
      period: "Néogène",
      epoque: "Miocène",
      etage: "Aquitanien",
      image: "",
      description: "",
    },
  ],

  Chattien: [
    {
      name: "",
      period: "Paléogène",
      epoque: "Oligocène",
      etage: "Chattien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Paléogène",
      epoque: "Oligocène",
      etage: "Chattien",
      image: "",
      description: "",
    },
  ],
  Rupélien: [
    {
      name: "",
      period: "Paléogène",
      epoque: "Oligocène",
      etage: "Rupélien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Paléogène",
      epoque: "Oligocène",
      etage: "Rupélien",
      image: "",
      description: "",
    },
  ],
  Priabonien: [
    {
      name: "",
      period: "Paléogène",
      epoque: "Eocène",
      etage: "Priabonien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Paléogène",
      epoque: "Eocène",
      etage: "Priabonien",
      image: "",
      description: "",
    },
  ],
  Bartonien: [
    {
      name: "",
      period: "Paléogène",
      epoque: "Eocène",
      etage: "Bartonien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Paléogène",
      epoque: "Eocène",
      etage: "Bartonien",
      image: "",
      description: "",
    },
  ],
  Lutétien: [
    {
      name: "",
      period: "Paléogène",
      epoque: "Eocène",
      etage: "Lutétien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Paléogène",
      epoque: "Eocène",
      etage: "Lutétien",
      image: "",
      description: "",
    },
  ],
  Yprésien: [
    {
      name: "",
      period: "Paléogène",
      epoque: "Eocène",
      etage: "Yprésien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Paléogène",
      epoque: "Eocène",
      etage: "Yprésien",
      image: "",
      description: "",
    },
  ],
  Thanétien: [
    {
      name: "",
      period: "Paléogène",
      epoque: "Paléocène",
      etage: "Thanétien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Paléogène",
      epoque: "Paléocène",
      etage: "Thanétien",
      image: "",
      description: "",
    },
  ],
  Sélandien: [
    {
      name: "",
      period: "Paléogène",
      epoque: "Paléocène",
      etage: "Sélandien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Paléogène",
      epoque: "Paléocène",
      etage: "Sélandien",
      image: "",
      description: "",
    },
  ],
  Danien: [
    {
      name: "",
      period: "Paléogène",
      epoque: "Paléocène",
      etage: "Danien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Paléogène",
      epoque: "Paléocène",
      etage: "Danien",
      image: "",
      description: "",
    },
  ],
  Maastrichtien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Maastrichtien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Maastrichtien",
      image: "",
      description: "",
    },
  ],
  Campanien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Campanien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Campanien",
      image: "",
      description: "",
    },
  ],
  Santonien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Santonien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Santonien",
      image: "",
      description: "",
    },
  ],
  Coniacien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Coniacien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Coniacien",
      image: "",
      description: "",
    },
  ],
  Turonien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Turonien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Turonien",
      image: "",
      description: "",
    },
  ],
  Cénomanien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Cénomanien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Supérieur",
      etage: "Cénomanien",
      image: "",
      description: "",
    },
  ],
  Albien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Albien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Albien",
      image: "",
      description: "",
    },
  ],
  Aptien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Aptien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Aptien",
      image: "",
      description: "",
    },
  ],
  Barrémien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Barrémien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Barrémien",
      image: "",
      description: "",
    },
  ],
  Hauterivien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Hauterivien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Hauterivien",
      image: "",
      description: "",
    },
  ],
  Valanginien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Valanginien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Valanginien",
      image: "",
      description: "",
    },
  ],
  Berriasien: [
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Berriasien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Crétacé",
      epoque: "Inférieur",
      etage: "Berriasien",
      image: "",
      description: "",
    },
  ],
  Tithonien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Supérieur",
      etage: "Tithonien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Supérieur",
      etage: "Tithonien",
      image: "",
      description: "",
    },
  ],
  Kimméridgien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Supérieur",
      etage: "Kimméridgien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Supérieur",
      etage: "Kimméridgien",
      image: "",
      description: "",
    },
  ],
  Oxfordien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Supérieur",
      etage: "Oxfordien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Supérieur",
      etage: "Oxfordien",
      image: "",
      description: "",
    },
  ],
  Callovien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Moyen",
      etage: "Callovien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Moyen",
      etage: "Callovien",
      image: "",
      description: "",
    },
  ],
  Bathonien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Moyen",
      etage: "Bathonien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Moyen",
      etage: "Bathonien",
      image: "",
      description: "",
    },
  ],
  Bajocien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Moyen",
      etage: "Bajocien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Moyen",
      etage: "Bajocien",
      image: "",
      description: "",
    },
  ],
  Aalénien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Moyen",
      etage: "Aalénien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Moyen",
      etage: "Aalénien",
      image: "",
      description: "",
    },
  ],
  Toarcien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Inférieur",
      etage: "Toarcien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Inférieur",
      etage: "Toarcien",
      image: "",
      description: "",
    },
  ],
  Pliensbachien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Inférieur",
      etage: "Pliensbachien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Inférieur",
      etage: "Pliensbachien",
      image: "",
      description: "",
    },
  ],
  Sinémurien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Inférieur",
      etage: "Sinémurien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Inférieur",
      etage: "Sinémurien",
      image: "",
      description: "",
    },
  ],
  Hettangien: [
    {
      name: "",
      period: "Jurassique",
      epoque: "Inférieur",
      etage: "Hettangien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Jurassique",
      epoque: "Inférieur",
      etage: "Hettangien",
      image: "",
      description: "",
    },
  ],
  Rhétien: [
    {
      name: "",
      period: "Trias",
      epoque: "Supérieur",
      etage: "Rhétien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Trias",
      epoque: "Supérieur",
      etage: "Rhétien",
      image: "",
      description: "",
    },
  ],

  Norien: [
    {
      name: "",
      period: "Trias",
      epoque: "Supérieur",
      etage: "Norien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Trias",
      epoque: "Supérieur",
      etage: "Norien",
      image: "",
      description: "",
    },
  ],
  Carnien: [
    {
      name: "",
      period: "Trias",
      epoque: "Supérieur",
      etage: "Carnien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Trias",
      epoque: "Supérieur",
      etage: "Carnien",
      image: "",
      description: "",
    },
  ],
  Ladinien: [
    {
      name: "",
      period: "Trias",
      epoque: "Moyen",
      etage: "Ladinien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Trias",
      epoque: "Moyen",
      etage: "Ladinien",
      image: "",
      description: "",
    },
  ],
  Anisien: [
    {
      name: "",
      period: "Trias",
      epoque: "Moyen",
      etage: "Anisien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Trias",
      epoque: "Moyen",
      etage: "Anisien",
      image: "",
      description: "",
    },
  ],
  Olénékien: [
    {
      name: "",
      period: "Trias",
      epoque: "Inférieur",
      etage: "Olénékien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Trias",
      epoque: "Inférieur",
      etage: "Olénékien",
      image: "",
      description: "",
    },
  ],
  Indusien: [
    {
      name: "",
      period: "Trias",
      epoque: "Inférieur",
      etage: "Indusien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Trias",
      epoque: "Inférieur",
      etage: "Indusien",
      image: "",
      description: "",
    },
  ],
  Changhsingien: [
    {
      name: "",
      period: "Permien",
      epoque: "Lopingien",
      etage: "Changhsingien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Permien",
      epoque: "Lopingien",
      etage: "Changhsingien",
      image: "",
      description: "",
    },
  ],
  Wuchiapingien: [
    {
      name: "",
      period: "Permien",
      epoque: "Lopingien",
      etage: "Wuchiapingien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Permien",
      epoque: "Lopingien",
      etage: "Wuchiapingien",
      image: "",
      description: "",
    },
  ],
  Capitanien: [
    {
      name: "",
      period: "Permien",
      epoque: "Guadalupien",
      etage: "Capitanien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Permien",
      epoque: "Guadalupien",
      etage: "Capitanien",
      image: "",
      description: "",
    },
  ],
  Wordien: [
    {
      name: "",
      period: "Permien",
      epoque: "Guadalupien",
      etage: "Wordien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Permien",
      epoque: "Guadalupien",
      etage: "Wordien",
      image: "",
      description: "",
    },
  ],
  Roadien: [
    {
      name: "",
      period: "Permien",
      epoque: "Guadalupien",
      etage: "Roadien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Permien",
      epoque: "Guadalupien",
      etage: "Roadien",
      image: "",
      description: "",
    },
  ],
  Kungurien: [
    {
      name: "",
      period: "Permien",
      epoque: "Cisuralien",
      etage: "Kungurien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Permien",
      epoque: "Cisuralien",
      etage: "Kungurien",
      image: "",
      description: "",
    },
  ],
  Artinskien: [
    {
      name: "",
      period: "Permien",
      epoque: "Cisuralien",
      etage: "Artinskien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Permien",
      epoque: "Cisuralien",
      etage: "Artinskien",
      image: "",
      description: "",
    },
  ],
  Sakmarien: [
    {
      name: "",
      period: "Permien",
      epoque: "Cisuralien",
      etage: "Sakmarien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Permien",
      epoque: "Cisuralien",
      etage: "Sakmarien",
      image: "",
      description: "",
    },
  ],
  Assélien: [
    {
      name: "",
      period: "Permien",
      epoque: "Cisuralien",
      etage: "Assélien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Permien",
      epoque: "Cisuralien",
      etage: "Assélien",
      image: "",
      description: "",
    },
  ],
  Gzhélien: [
    {
      name: "",
      period: "Carbonifère",
      epoque: "Pennsylvanien",
      etage: "Gzhélien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Carbonifère",
      epoque: "Pennsylvanien",
      etage: "Gzhélien",
      image: "",
      description: "",
    },
  ],
  Kasimovien: [
    {
      name: "",
      period: "Carbonifère",
      epoque: "Pennsylvanien",
      etage: "Kasimovien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Carbonifère",
      epoque: "Pennsylvanien",
      etage: "Kasimovien",
      image: "",
      description: "",
    },
  ],
  Moscovien: [
    {
      name: "",
      period: "Carbonifère",
      epoque: "Pennsylvanien",
      etage: "Moscovien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Carbonifère",
      epoque: "Pennsylvanien",
      etage: "Moscovien",
      image: "",
      description: "",
    },
  ],
  Bachkirien: [
    {
      name: "",
      period: "Carbonifère",
      epoque: "Pennsylvanien",
      etage: "Bachkirien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Carbonifère",
      epoque: "Pennsylvanien",
      etage: "Bachkirien",
      image: "",
      description: "",
    },
  ],

  Serpukhovien: [
    {
      name: "",
      period: "Carbonifère",
      epoque: "Mississippien",
      etage: "Serpukhovien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Carbonifère",
      epoque: "Mississippien",
      etage: "Serpukhovien",
      image: "",
      description: "",
    },
  ],
  Viséen: [
    {
      name: "",
      period: "Carbonifère",
      epoque: "Mississippien",
      etage: "Viséen",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Carbonifère",
      epoque: "Mississippien",
      etage: "Viséen",
      image: "",
      description: "",
    },
  ],
  Tournaisien: [
    {
      name: "",
      period: "Carbonifère",
      epoque: "Mississippien",
      etage: "Tournaisien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Carbonifère",
      epoque: "Mississippien",
      etage: "Tournaisien",
      image: "",
      description: "",
    },
  ],
  Famennien: [
    {
      name: "",
      period: "Dévonien",
      epoque: "Supérieur",
      etage: "Famennien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Dévonien",
      epoque: "Supérieur",
      etage: "Famennien",
      image: "",
      description: "",
    },
  ],
  Frasnien: [
    {
      name: "",
      period: "Dévonien",
      epoque: "Supérieur",
      etage: "Frasnien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Dévonien",
      epoque: "Supérieur",
      etage: "Frasnien",
      image: "",
      description: "",
    },
  ],
  Givétien: [
    {
      name: "",
      period: "Dévonien",
      epoque: "Moyen",
      etage: "Givétien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Dévonien",
      epoque: "Moyen",
      etage: "Givétien",
      image: "",
      description: "",
    },
  ],
  Eifélien: [
    {
      name: "",
      period: "Dévonien",
      epoque: "Moyen",
      etage: "Eifélien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Dévonien",
      epoque: "Moyen",
      etage: "Eifélien",
      image: "",
      description: "",
    },
  ],
  Emsien: [
    {
      name: "",
      period: "Dévonien",
      epoque: "Inférieur",
      etage: "Emsien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Dévonien",
      epoque: "Inférieur",
      etage: "Emsien",
      image: "",
      description: "",
    },
  ],
  Praguien: [
    {
      name: "",
      period: "Dévonien",
      epoque: "Inférieur",
      etage: "Praguien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Dévonien",
      epoque: "Inférieur",
      etage: "Praguien",
      image: "",
      description: "",
    },
  ],
  Lochkovien: [
    {
      name: "",
      period: "Dévonien",
      epoque: "Inférieur",
      etage: "Lochkovien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Dévonien",
      epoque: "Inférieur",
      etage: "Lochkovien",
      image: "",
      description: "",
    },
  ],
  Pridolien: [
    {
      name: "",
      period: "Silurien",
      epoque: "Pridoli",
      etage: "Pridolien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Silurien",
      epoque: "Pridoli",
      etage: "Pridolien",
      image: "",
      description: "",
    },
  ],
  Ludfordien: [
    {
      name: "",
      period: "Silurien",
      epoque: "Ludlow",
      etage: "Ludfordien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Silurien",
      epoque: "Ludlow",
      etage: "Ludfordien",
      image: "",
      description: "",
    },
  ],
  Gorstien: [
    {
      name: "",
      period: "Silurien",
      epoque: "Ludlow",
      etage: "Gorstien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Silurien",
      epoque: "Ludlow",
      etage: "Gorstien",
      image: "",
      description: "",
    },
  ],
  Homérien: [
    {
      name: "",
      period: "Silurien",
      epoque: "Wenlock",
      etage: "Homérien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Silurien",
      epoque: "Wenlock",
      etage: "Homérien",
      image: "",
      description: "",
    },
  ],
  Sheinwoodien: [
    {
      name: "",
      period: "Silurien",
      epoque: "Wenlock",
      etage: "Sheinwoodien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Silurien",
      epoque: "Wenlock",
      etage: "Sheinwoodien",
      image: "",
      description: "",
    },
  ],
  Télychien: [
    {
      name: "",
      period: "Silurien",
      epoque: "Llandovery",
      etage: "Télychien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Silurien",
      epoque: "Llandovery",
      etage: "Télychien",
      image: "",
      description: "",
    },
  ],

  Aéronien: [
    {
      name: "",
      period: "Silurien",
      epoque: "Llandovery",
      etage: "Aéronien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Silurien",
      epoque: "Llandovery",
      etage: "Aéronien",
      image: "",
      description: "",
    },
  ],

  Rhuddanien: [
    {
      name: "",
      period: "Silurien",
      epoque: "Llandovery",
      etage: "Rhuddanien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Silurien",
      epoque: "Llandovery",
      etage: "Rhuddanien",
      image: "",
      description: "",
    },
  ],

  Hirnantien: [
    {
      name: "",
      period: "Ordovicien",
      epoque: "Supérieur",
      etage: "Hirnantien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Ordovicien",
      epoque: "Supérieur",
      etage: "Hirnantien",
      image: "",
      description: "",
    },
  ],
  Katien: [
    {
      name: "",
      period: "Ordovicien",
      epoque: "Supérieur",
      etage: "Katien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Ordovicien",
      epoque: "Supérieur",
      etage: "Katien",
      image: "",
      description: "",
    },
  ],
  Sandbien: [
    {
      name: "",
      period: "Ordovicien",
      epoque: "Supérieur",
      etage: "Sandbien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Ordovicien",
      epoque: "Supérieur",
      etage: "Sandbien",
      image: "",
      description: "",
    },
  ],
  Darriwilien: [
    {
      name: "",
      period: "Ordovicien",
      epoque: "Moyen",
      etage: "Darriwilien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Ordovicien",
      epoque: "Moyen",
      etage: "Darriwilien",
      image: "",
      description: "",
    },
  ],
  Dapingien: [
    {
      name: "",
      period: "Ordovicien",
      epoque: "Moyen",
      etage: "Dapingien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Ordovicien",
      epoque: "Moyen",
      etage: "Dapingien",
      image: "",
      description: "",
    },
  ],
  Floien: [
    {
      name: "",
      period: "Ordovicien",
      epoque: "Inférieur",
      etage: "Floien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Ordovicien",
      epoque: "Inférieur",
      etage: "Floien",
      image: "",
      description: "",
    },
  ],
  Trémadocien: [
    {
      name: "",
      period: "Ordovicien",
      epoque: "Inférieur",
      etage: "Trémadocien",
      image: "",
      description: "",
    },
    {
      name: "",
      period: "Ordovicien",
      epoque: "Inférieur",
      etage: "Trémadocien",
      image: "",
      description: "",
    },
  ],
  Etage10: [
    {
      name: "",
      period: "Cambrien",
      epoque: "Furongien",
      etage: "Etage 10",
      image: "",
      description: "",
    },
  ],
  Jiangshanien: [
    {
      name: "",
      period: "Cambrien",
      epoque: "Furongien",
      etage: "Jiangshanien",
      image: "",
      description: "",
    },
  ],
  Paibien: [
    {
      name: "",
      period: "Cambrien",
      epoque: "Furongien",
      etage: "Paibien",
      image: "",
      description: "",
    },
  ],
  Guzhangien: [
    {
      name: "Peytoia",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Guzhangien",
      image: "./images/Peytoia.jpeg",
      description:
        "Peytoia possédait une bouche munie de crocs acérés qui leur permettaient de capturer et de dévorer leurs proies. Ces animaux ont joué un rôle important dans les écosystèmes marins de l'époque en tant que prédateurs dominants.",
    },
  ],
  Drumien: [
    {
      name: "",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Drumien",
      image: "",
      description: "",
    },
  ],
  Wuliuen: [
    {
      name: "Aysheaia",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Wuliuen",
      image: "./images/Aysheaia.jpeg",
      description:
        "Aysheaia était caractérisé par son corps segmenté et allongé, avec des appendices en forme de pattes sur chaque segment. Ces créatures étaient dépourvues de membres articulés et possédaient une bouche située à l'extrémité antérieure de leur corps. Aysheaia était probablement un prédateur, se nourrissant de petits organismes marins.",
    },
    {
      name: "Anomalocaris",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Wuliuen",
      image: "./images/Anomalocaris.jpeg",
      description:
        "Anomalocaris possédait un corps allongé avec une paire d'yeux composés, une bouche munie de nombreuses pointes et des appendices en forme de nageoires. Il mesurait entre 2 et 4 mètres de longueur et se nourrissait probablement de petits organismes marins. Anomalocaris est considéré comme l'un des premiers prédateurs de grande taille de l'histoire de la vie sur Terre.",
    },
    {
      name: "Hallucigenia",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Wuliuen",
      image: "./images/Hallucigenia.jpeg",
      description:
        "Cet animal marin à la silouhette atypique avait un corps allongé avec des épines sur le dos et de nombreuses pattes pointues. Ses caractéristiques étranges et inhabituelles en ont fait un fossile fascinant pour les scientifiques.",
    },
    {
      name: "Marrella",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Wuliuen",
      image: "./images/Marrella.jpeg",
      description:
        "Cette petite créature marine mesurant environ 5 centimètres de longueur possédait un corps allongé et divisé en segments, avec de multiples paires de pattes fines et ramifiées. Sa tête était munie d'antennes et de mandibules. On pense que Marrella était un animal filtreur se nourrissant de particules alimentaires présentes dans l'eau. Ses fossiles fournissent des informations précieuses sur la biodiversité au cours de cette période ancienne de l'histoire de la Terre.",
    },
    {
      name: "Nectocaris",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Wuliuen",
      image: "./images/Nectocaris.jpeg",
      description:
        "Cet de petite taille, mesurant environ 10 centimètres de longueur, avec un corps allongé et divisé en segments, possédait de nombreux appendices, y compris des nageoires latérales et des tentacules sur sa tête, qui étaient probablement utilisés pour capturer sa nourriture. Nectocaris est considéré comme l'un des premiers exemples connus de céphalopodes, une famille d'animaux marins qui comprend les poulpes, les calmars et les seiches. Son fossile a été découvert dans des gisements en Australie et au Canada, fournissant des informations précieuses sur la diversité des formes de vie au cours du Cambrien.",
    },
    {
      name: "Odontogriphus",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Wuliuen",
      image: "./images/Odontogriphus.jpeg",
      description:
        "Odontogriphus avait un corps allongé en forme de ver, mesurant jusqu'à 12 centimètres de long. Il possédait une bouche équipée de dents coniques, appelées conodontes, qui étaient utilisées pour saisir et broyer sa nourriture. Odontogriphus joue un rôle important dans la compréhension de l'évolution des conodontes et des premiers vertébrés.",
    },
    {
      name: "Opabinia",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Wuliuen",
      image: "./images/Opabinia.jpeg",
      description:
        "C'était un arthropode étrange et unique, mesurant environ 5 centimètres de long. Opabinia avait un corps allongé avec une tête en forme de trompe qui possédait deux grands yeux composés et une bouche dirigée vers le bas. Sur sa tête, il y avait également cinq yeux plus petits. Il possédait de nombreux membres minces et articulés, dont un pair de pinces à l'avant. Opabinia était dotée d'un appendice en forme de queue qui ressemblait à une plume et qui était probablement utilisé pour se propulser dans l'eau. Cette créature énigmatique est considérée comme l'un des premiers exemples connus de formes de vie complexe de l'ère cambrienne.",
    },
    {
      name: "Pikaia",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Wuliuen",
      image: "./images/Pikaia.jpeg",
      description:
        "Pikaia était un animal segmenté en forme de ver, mesurant environ 5 à 7 centimètres de long. Il possédait un corps allongé avec une symétrie bilatérale et était pourvu d'une queue en forme de nageoire. Il n'avait pas de véritable colonne vertébrale, mais possédait une structure semblable à une tige appelée 'notochorde', qui est considérée comme un précurseur de la colonne vertébrale. Pikaia vivait dans les mers peu profondes de la période cambrienne et se nourrissait probablement de particules organiques en suspension dans l'eau.",
    },
    {
      name: "Sidneyia",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Wuliuen",
      image: "./images/Sidneyia.jpeg",
      description:
        "Sidneyia possède un corps allongé et segmenté, recouvert d'une carapace dure, et il est considéré comme l'un des premiers prédateurs connus. Sidneyia avait une paire d'antennes à l'avant de sa tête, suivie de plusieurs paires de pattes. Il mesurait généralement entre 2 et 7 centimètres de long. ",
    },
    {
      name: "Wiwaxia",
      period: "Cambrien",
      epoque: "Miaolingien",
      etage: "Wuliuen",
      image: "./images/Wiwaxia.jpeg",
      description:
        "Wiwaxia était une créature marine qui avait un corps ovale couvert de plaques dures et pointues, semblables à des écailles. Wiwaxia possédait de nombreux piquants défensifs sur son dos et une rangée de petits appendices en forme de brosse sur ses côtés, qui l'aidaient à filtrer les particules de nourriture de l'eau. Il se déplaçait en utilisant des appendices minces situés sur son ventre. ",
    },
  ],
  Etage4: [
    {
      name: "",
      period: "Cambrien",
      epoque: "Série 2",
      etage: "Etage 4",
      image: "",
      description: "",
    },
  ],
  Etage3: [
    {
      name: "",
      period: "Cambrien",
      epoque: "Série 2",
      etage: "Etage 3",
      image: "",
      description: "",
    },
  ],
  Etage2: [
    {
      name: "Conodonta",
      period: "Cambrien",
      epoque: "Terreneuvien",
      etage: "Etage 2",
      image: "./images/Conodontes.jpg",
      description:
        "Les conodontes sont des microfossiles marins éteints qui ressemblaient à de petites dents ou à des éléments dentaires. De la taille d'un grain de riz pour les plus gros spécimens, ils se sont éteints au Trias mais sont aujourd'hui considérés comme des indices stratigraphiques précieux pour la datation des roches sédimentaires. Les conodontes étaient des animaux primitifs, sans mâchoires, qui jouaient probablement un rôle dans la capture de proies et la digestion.",
    },
    {
      name: "Trilobite",
      period: "Cambrien",
      epoque: "Terreneuvien",
      etage: "Etage 2",
      image: "./images/Trilobite.jpeg",
      description:
        "Un trilobite est un ancien groupe d'arthropodes marins qui ont vécu il y a des millions d'années. Ces animaux étaient caractérisés par un corps segmenté en trois parties distinctes, d'où leur nom. Ils possédaient une carapace externe dure et étaient munis de multiples paires de pattes. Les trilobites ont existé pendant une période allant du Cambrien au Permien, et ils sont considérés comme l'un des premiers organismes complexes existants. Leurs fossiles nous permettent de retracer leur histoire et d'en apprendre davantage sur la vie marine préhistorique.",
    },
  ],
  Fortunien: [
    {
      name: "Halkieria",
      period: "Cambrien",
      epoque: "Terreneuvien",
      etage: "Fortunien",
      image: "./images/Halkieria.jpeg",
      description:
        "Halkieria appartenait au groupe des animaux à corps mou et possédait une coquille en forme de bouclier. Halkieria avait une symétrie bilatérale et se déplaçait en utilisant un pied musclé. Il possédait également une bouche, des organes digestifs et un système nerveux primitif. Bien que petit, Halkieria occupait un rôle important dans les écosystèmes marins de l'époque.",
    },
    {
      name: "Haikouichthys",
      period: "Cambrien",
      epoque: "Terreneuvien",
      etage: "Fortunien",
      image: "./images/Haikouichthys.jpeg",
      description:
        "Haikouichthys était caractérisé par un corps allongé et mince, dépourvu de mâchoires et d'écailles. Haikouichthys possédait une fente branchiale unique de chaque côté de son corps, ce qui suggère qu'il respirait principalement par branchies. Il est considéré comme l'un des premiers vertébrés connus.",
    },
    {
      name: "Helcionelloida",
      period: "Cambrien",
      epoque: "Terreneuvien",
      etage: "Fortunien",
      image: "./images/Helcionelloida.jpeg",
      description:
        "Mollusques primitifs avec une coquille en forme de cône et un corps mou à l'intérieur, les Helcionelloida étaient de petite taille et avaient une symétrie bilatérale. Ils sont considérés comme l'un des ancêtres des gastéropodes, un groupe comprenant des escargots et des limaces. Malgré leur disparition, leur étude permet de mieux comprendre diversité de la vie marine ancienne.",
    },
    {
      name: "Hyolitha",
      period: "Cambrien",
      epoque: "Terreneuvien",
      etage: "Fortunien",
      image: "./images/Hyolitha.jpeg",
      description:
        "Les Hyolitha sont un groupe éteint d'animaux marins qui ressemblaient à des coquillages en forme de cônes avec une coquille en forme de tube. On pense qu'ils étaient fixés au fond de l'océan par une partie de leur coquille, tandis que leur corps se trouvait à l'intérieur du tube. Les Hyolitha étaient de petites créatures et leur mode de vie exact ainsi que leur parenté avec d'autres groupes d'animaux marins restent encore en grande partie mystérieux.",
    },
  ],
};
